<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="EmoteRanking\Queries\**" />
    <EmbeddedResource Remove="EmoteRanking\Queries\**" />
    <None Remove="EmoteRanking\Queries\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="13.1.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.18" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.18" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.18" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OlliBot.Domain\OlliBot.Domain.csproj" />
  </ItemGroup>

</Project>
